.\" Manpage for procmon.
.TH man 8 "07/16/2020" "0.1" "procmon manpage"
.SH NAME
procmon \- syscall tracing diagnostics tool
.SH SYNOPSIS
procmon [OPTIONS...]
      -h                       Prints this help screen
      -p/--pids                Comma separated list of process ids to monitor
      -e/--events              Comma separated list of system calls to monitor
      -c/--collect [FILEPATH]  Option to start Procmon in a headless mode
      -f/--file FILEPATH       Open a Procmon trace file
.SH DESCRIPTION
Procmon is a Linux reimagining of the classic Procmon tool from the Sysinternals suite of tools for Windows. Procmon provides a convenient and efficient way for Linux developers to trace the syscall activity on the system.