.\" Manpage for procmon.
.TH man 8 "04/22/2020" "0.9" "procmon manpage"
.SH NAME
procmon \- syscall tracing diagnostics tool
.SH SYNOPSIS
procmon [OPTIONS...]
      -h          Prints this help screen
      -p/--pids   Comma separated list of process ids to monitor
.SH DESCRIPTION
Procmon is a Linux reimagining of the classic Procmon tool from the Sysinternals suite of tools for Windows. Procmon provides a convenient and efficient way for Linux developers to trace the syscall activity on the system.