steps:
- script: |
   export LLVM_DIR=/usr/lib/llvm-6.0/lib/cmake/llvm
   export REVISION=$(Build.BuildId)
   sed -i "s/999999/$REVISION/g" $(Build.SourcesDirectory)/CMakeLists.txt
   mkdir $(Build.SourcesDirectory)/build && cd $(Build.SourcesDirectory)/build
   cmake ..
   make
  displayName: "Build Procmon binaries"
