parameters:
- name: srcPath
  type: string
  default: '.'
- name: builddir
  type: string
  default: 'procdump_build'  
  
steps:
- script: |
   export LLVM_DIR=/usr/lib/llvm-6.0/lib/cmake/llvm
   export REVISION=$(Build.BuildId)
   sed -i "s/999999/$REVISION/g" ${{ parameters.srcPath }}/CMakeLists.txt
   mkdir -p ${{ parameters.srcPath }}/${{ parameters.builddir }} && cd ${{ parameters.srcPath }}/${{ parameters.builddir }}
   cmake ..
   make
  displayName: "Build Procmon binaries"
